import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class MediaSkillTests(unittest.TestCase):
    def test_conversational_choices_use_native_clarify_without_pseudo_markup(self):
        skill = (ROOT / "shared/skills/media/SKILL.md").read_text(encoding="utf-8")
        normalized = " ".join(skill.split())

        self.assertIn("native `clarify`", skill)
        self.assertIn("you MUST use Hermes' native", skill)
        self.assertIn("one episode", skill)
        self.assertIn("whole season", skill)
        self.assertIn("up to five translations", normalized)
        self.assertIn("Do not ask any of these questions as a plain-text list", skill)
        self.assertIn("Never print XML-like Telegram quick-reply markup", skill)
        self.assertNotIn("<telegram-quick-replies>", skill)
        self.assertIn("Job-card actions are owned by `media-notifier`", normalized)
        self.assertIn("query Rezka and Prowlarr immediately", skill)
        self.assertIn("one unified ranked list", normalized)
        self.assertIn("without asking where to search", skill)
        self.assertIn("explicit overrides", skill)

    def test_job_cards_are_deterministic_and_not_repeated_by_the_agent(self):
        skill = (ROOT / "shared/skills/media/SKILL.md").read_text(encoding="utf-8")
        normalized = " ".join(skill.split())

        self.assertIn("Buttons on job cards are deterministic", skill)
        self.assertIn("never generated by the LLM", skill)
        self.assertIn("`Details` edits the existing card", skill)
        self.assertIn("`Back` restores its compact view", skill)
        self.assertIn(
            "never repeat or summarize notifier-owned progress",
            normalized.lower(),
        )
        self.assertIn("never silently switch providers", normalized.lower())
        self.assertIn("automatic-download tracking", normalized)

    def test_prowlarr_single_episode_selection_keeps_exact_coordinates(self):
        skill = (ROOT / "shared/skills/media/SKILL.md").read_text(encoding="utf-8")

        self.assertIn(
            "Prowlarr episode: pass `season` and `episode` to `media_download`",
            skill,
        )
        self.assertIn(
            "qBittorrent downloads only the matching video file",
            skill,
        )


if __name__ == "__main__":
    unittest.main()
