## https://fariszr.com/en/docker-smb-network-discovery/

services:
  samba:
    image: crazymax/samba
    container_name: samba
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      - "SAMBA_LOG_LEVEL=0"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    volumes:
      - ./config:/data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/internal:/mnt/share/internal
      - /mnt/usb_drive:/mnt/share/usb_drive

  wsdd:
    container_name: samba-wsdd
    image: jonasped/wsdd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    environment:
      - 'HOSTNAME=docker'

  avahi:
    container_name: samba-avahi
    image: ydkn/avahi
    hostname: docker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    volumes:
      - ./config/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf:ro
      - ./config/avahi-services:/etc/avahi/services:ro
