services:
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    secrets:
      - cf_dns_api_token
    networks:
      proxy:
        aliases:
          - freedium.${DOCKER_DOMAIN}
    ports:
      # HTTP & HTTPS
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/traefik.yml:ro"
      - "./config/config.yml:/config.yml:ro"
      - "./config/acme.json:/acme.json"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

secrets:
  cf_dns_api_token:
    file: ./secrets/cf_dns_api_token

networks:
  proxy:
    external: true
