services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    volumes:
      - ./data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    healthcheck:
      test: [CMD, hbbs, --help]
      interval: 30s
      timeout: 5s
      retries: 3

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    volumes:
      - ./data:/root
    network_mode: "host"
    healthcheck:
      test: [CMD, hbbr, --help]
      interval: 30s
      timeout: 5s
      retries: 3
