#!/bin/sh

set -eu

action="${1:-${script_type:-}}"
up_file="${2:?up marker path is required}"
connected_file="${3:?connected marker path is required}"
ready_file="${4:?firewall ready marker path is required}"

case "$action" in
    up|route-up)
        : > "$up_file"
        : > "$connected_file"
        rm -f "$ready_file"
        chmod 0644 "$up_file" "$connected_file"
        ;;
    down|pre-down)
        rm -f "$up_file"
        rm -f "$ready_file"
        ;;
    *)
        exit 0
        ;;
esac
